### ISSUE TITLE
missing mmglpsrv

### ISSUE THREAD

**Issue by gregzuro** [negativo17/makemkv#1]
What is this binary?
https://github.com/negativo17/makemkv/blob/b33b9c98f8367e9809fd5ed4f8d8da622fe382f6/makemkv.spec#L147

I can't find anything about it.

Also: it's missing from my install on Debian Bullseye (via mkvtoolnix).

Any suggestions for a remedy?

thanks,

**Comment by scaronni** [comment]
This space is to open issues on the packages i'm providing.
The binary is part of the MakeMKV tarball, and I include it, so not an issue.
